#!/bin/env ruby
# frozen_string_literal: true

require 'thor'
require 'require_all'
require 'rake/testtask'
require_rel 'lib/aoc2019'

def challenge(day)
  day_padded = day.to_s.rjust(2, '0')
  puts "Challenge Day #{day_padded}"
  input = IO.read("../input/#{day_padded}.txt")
  challenge = Kernel.const_get("Aoc2019::Day#{day_padded}")
  puts "Part One: #{challenge.part_one(input)}"
  puts "Part Two: #{challenge.part_two(input)}"
rescue Errno::ENOENT
  puts 'Incomplete'
end

task default: :test

desc 'Run challenge 1'
task 'challenge', [:day] do |_, args|
  if args.day
    challenge(args.day)
  else
    1.upto(24) { |day| challenge(day) }
  end
end

Rake::TestTask.new do |task|
  task.pattern = 'test/aoc2019/*_test.rb'
end
